version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/mydbTODO:DEFINE
      - DB_USERNAME=TODO:DEFINE
      - DB_PASSWORD=TODO:DEFINE
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=TODO:DEFINE
      - POSTGRES_USER=TODO:DEFINE
      - POSTGRES_PASSWORD=TODO:DEFINE
    ports:
      - "5432:5432"
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=TODO:DEFINE'
      - 'RABBITMQ_DEFAULT_USER=TODO:DEFINE'
    ports:
      - "5672:5672"
