version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:postgresql://db:5432/surfwear_db
      - DB_USERNAME=user
      - DB_PASSWORD=user
    depends_on:
      - db
    network_mode: bridge
    links:
      - db:db
      - rabbitmq:rabbitmq
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=surfwear_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    network_mode: bridge
  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_DEFAULT_USER=root
    ports:
      - "5672:5672"
    network_mode: bridge
    links:
      - db:db
